---
title: "Unemployment"
output: html_document
---

```{r setup, include=FALSE}
load(".RData")
knitr::opts_chunk$set(echo = TRUE)
```

# %of the workforce unemployed each month from 2016 to 2018 in Turkey

Year1 <-c(11.1,	10.9,	10.1,	9.3,	9.4,	10.2,	10.7,	11.3,	11.3,	11.8,	12.1,	12.7)

```{r Year1}
plot(Year1, type="h", axes = TRUE, xlab="Months", ylab="Unemployment (%)")
```
Year2 <-c(13,	12.6,	11.7,	10.5,	10.2,	10.2,	10.7,	10.6,	10.6,	10.3,	10.3,	10.4)

```{r Year2}
plot(Year2,  type="h", axes = TRUE, xlab="Months", ylab="Unemployment (%)")
```

Year3 <-c(10.8,	10.6,	10.1,	9.6,	9.7,	10.2,	10.8,	11.1,	11.4,	11.6,	12.3,	13.5)

```{r Year3}
plot(Year3,  type="h", axes = TRUE, xlab="Months", ylab="Unemployment (%)")
```

#Popularity of website "Kariyer.net" that particular year obtained from Google Trends (Each week-for Turkey)
Trends1 <-c(84
,73
,70
,76
,64
,94
,87
,84
,77
,84
,67
,70
,80
,63
,64
,64
,67
,60
,56
,57
,77
,69
,65
,84
,83
,67
,47
,77
,70
,89
,77
,68
,78
,65
,73
,77
,36
,95
,70
,73
,86
,62
,67
,64
,70
,70
,62
,61
,63
,63
,56
,51)

```{r Trends1, echo=TRUE}
boxplot(Trends1)
```

Trends2 <-c(60
,55
,61
,59
,59
,76
,59
,56
,57
,59
,62
,62
,48
,59
,50
,49
,49
,46
,56
,59
,57
,61
,69
,77
,71
,59
,73
,72
,79
,83
,82
,85
,80
,86
,46
,76
,79
,72
,79
,71
,82
,61
,63
,71
,68
,66
,56
,61
,65
,63
,58
,58)
```{r boxYear1, echo=TRUE}
boxplot(Year1)
```

```{r Trends2, echo=TRUE}
boxplot(Trends2)
```

```{r boxYear2, echo=TRUE}
boxplot(Year2)
```

Trends3 <-c(58
,62
,57
,51
,61
,54
,62
,54
,59
,60
,56
,65
,55
,56
,53
,54
,56
,40
,44
,63
,52
,50
,54
,43
,65
,51
,55
,48
,47
,56
,49
,50
,30
,35
,56
,60
,51
,50
,50
,59
,61
,50
,64
,63
,70
,70
,91
,96
,82
,80
,97
,100
)


```{r Trends3, echo=TRUE}
boxplot(Trends3)
```


```{r boxYear3, echo=TRUE}
boxplot(Year3)
```





































